from PyQt5 import QtCore, QtGui, QtWidgets


class DiagnosticTabR3(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setObjectName("tab_diagnostic")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem7)
        self.frame_14 = QtWidgets.QFrame(self)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_14)
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.animator_input = QtWidgets.QLabel(self.frame_12)
        self.animator_input.setMinimumSize(QtCore.QSize(0, 0))
        self.animator_input.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.animator_input.setFont(font)
        self.animator_input.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.animator_input.setAlignment(QtCore.Qt.AlignCenter)
        self.animator_input.setObjectName("animator_input")
        self.verticalLayout_9.addWidget(self.animator_input)
        self.light_input = QtWidgets.QLabel(self.frame_12)
        self.light_input.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.light_input.setFont(font)
        self.light_input.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.light_input.setAlignment(QtCore.Qt.AlignCenter)
        self.light_input.setObjectName("light_input")
        self.verticalLayout_9.addWidget(self.light_input)
        self.reserve_1 = QtWidgets.QLabel(self.frame_12)
        self.reserve_1.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_1.setFont(font)
        self.reserve_1.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_1.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_1.setObjectName("reserve_1")
        self.verticalLayout_9.addWidget(self.reserve_1)
        self.reserve_2 = QtWidgets.QLabel(self.frame_12)
        self.reserve_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_2.setFont(font)
        self.reserve_2.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_2.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_2.setObjectName("reserve_2")
        self.verticalLayout_9.addWidget(self.reserve_2)
        self.reserve_3 = QtWidgets.QLabel(self.frame_12)
        self.reserve_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_3.setFont(font)
        self.reserve_3.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_3.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_3.setObjectName("sensor_3")
        self.verticalLayout_9.addWidget(self.reserve_3)
        self.ping_input = QtWidgets.QLabel(self.frame_12)
        self.ping_input.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ping_input.setFont(font)
        self.ping_input.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.ping_input.setAlignment(QtCore.Qt.AlignCenter)
        self.ping_input.setObjectName("ping_input")
        self.verticalLayout_9.addWidget(self.ping_input)
        self.horizontalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setVerticalSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.reserve5_label = QtWidgets.QLabel(self.frame_13)
        self.reserve5_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve5_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve5_label.setFont(font)
        self.reserve5_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve5_label.setObjectName("reserv5_label")
        self.verticalLayout_33.addWidget(self.reserve5_label)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.reserve5_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve5_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve5_off.setFont(font)
        self.reserve5_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve5_off.setObjectName("reserv5_off")
        self.reserve5_off.setDisabled(True)
        self.horizontalLayout_31.addWidget(self.reserve5_off)
        self.reserve5_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve5_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve5_on.setFont(font)
        self.reserve5_on.setObjectName("reserv5_on")
        self.reserve5_on.setDisabled(True)
        self.horizontalLayout_31.addWidget(self.reserve5_on)
        self.verticalLayout_33.addLayout(self.horizontalLayout_31)
        self.gridLayout_4.addLayout(self.verticalLayout_33, 2, 0, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.reserve7_label = QtWidgets.QLabel(self.frame_13)
        self.reserve7_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve7_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve7_label.setFont(font)
        self.reserve7_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve7_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve7_label.setObjectName("reserv7_label")
        self.verticalLayout_35.addWidget(self.reserve7_label)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.reserve7_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve7_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve7_off.setFont(font)
        self.reserve7_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve7_off.setObjectName("reserv7_off")
        self.reserve7_off.setDisabled(True)
        self.horizontalLayout_33.addWidget(self.reserve7_off)
        self.reserve7_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve7_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve7_on.setFont(font)
        self.reserve7_on.setObjectName("reserv7_on")
        self.reserve7_on.setDisabled(True)
        self.horizontalLayout_33.addWidget(self.reserve7_on)
        self.verticalLayout_35.addLayout(self.horizontalLayout_33)
        self.gridLayout_4.addLayout(self.verticalLayout_35, 2, 2, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.reserve6_label = QtWidgets.QLabel(self.frame_13)
        self.reserve6_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve6_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve6_label.setFont(font)
        self.reserve6_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve6_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve6_label.setObjectName("reserv6_label")
        self.verticalLayout_34.addWidget(self.reserve6_label)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.reserve6_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve6_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve6_off.setFont(font)
        self.reserve6_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve6_off.setObjectName("reserv6_off")
        self.reserve6_off.setDisabled(True)
        self.horizontalLayout_32.addWidget(self.reserve6_off)
        self.reserve6_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve6_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve6_on.setFont(font)
        self.reserve6_on.setObjectName("reserv6_on")
        self.reserve6_on.setDisabled(True)
        self.horizontalLayout_32.addWidget(self.reserve6_on)
        self.verticalLayout_34.addLayout(self.horizontalLayout_32)
        self.gridLayout_4.addLayout(self.verticalLayout_34, 2, 1, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.reserve3_label = QtWidgets.QLabel(self.frame_13)
        self.reserve3_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve3_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve3_label.setFont(font)
        self.reserve3_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve3_label.setObjectName("reserv3_label")
        self.verticalLayout_24.addWidget(self.reserve3_label)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.reserve3_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve3_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve3_off.setFont(font)
        self.reserve3_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve3_off.setObjectName("reserv3_off")
        self.reserve3_off.setDisabled(True)
        self.horizontalLayout_22.addWidget(self.reserve3_off)
        self.reserve3_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve3_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve3_on.setFont(font)
        self.reserve3_on.setObjectName("reserv3_on")
        self.reserve3_on.setDisabled(True)
        self.horizontalLayout_22.addWidget(self.reserve3_on)
        self.verticalLayout_24.addLayout(self.horizontalLayout_22)
        self.gridLayout_4.addLayout(self.verticalLayout_24, 1, 1, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.reserve4_label = QtWidgets.QLabel(self.frame_13)
        self.reserve4_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve4_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve4_label.setFont(font)
        self.reserve4_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve4_label.setObjectName("reserv4_label")
        self.verticalLayout_22.addWidget(self.reserve4_label)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.reserve4_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve4_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve4_off.setFont(font)
        self.reserve4_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve4_off.setObjectName("reserv4_off")
        self.reserve4_off.setDisabled(True)
        self.horizontalLayout_20.addWidget(self.reserve4_off)
        self.reserve4_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve4_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve4_on.setFont(font)
        self.reserve4_on.setObjectName("reserv4_on")
        self.reserve4_on.setDisabled(True)
        self.horizontalLayout_20.addWidget(self.reserve4_on)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.gridLayout_4.addLayout(self.verticalLayout_22, 1, 2, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.reserve2_label = QtWidgets.QLabel(self.frame_13)
        self.reserve2_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve2_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve2_label.setFont(font)
        self.reserve2_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve2_label.setObjectName("reserv2_label")
        self.verticalLayout_14.addWidget(self.reserve2_label)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.reserve2_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve2_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve2_off.setFont(font)
        self.reserve2_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve2_off.setObjectName("reserv2_off")
        self.reserve2_off.setDisabled(True)
        self.horizontalLayout_12.addWidget(self.reserve2_off)
        self.reserve2_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve2_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve2_on.setFont(font)
        self.reserve2_on.setObjectName("reserv2_on")
        self.reserve2_on.setDisabled(True)
        self.horizontalLayout_12.addWidget(self.reserve2_on)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.gridLayout_4.addLayout(self.verticalLayout_14, 1, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.mask_label = QtWidgets.QLabel(self.frame_13)
        self.mask_label.setMinimumSize(QtCore.QSize(0, 50))
        self.mask_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mask_label.setFont(font)
        self.mask_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.mask_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_label.setObjectName("mask_label")
        self.verticalLayout_13.addWidget(self.mask_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.mask_off = QtWidgets.QPushButton(self.frame_13)
        self.mask_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mask_off.setFont(font)
        self.mask_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.mask_off.setObjectName("mask_off")
        self.horizontalLayout_11.addWidget(self.mask_off)
        self.mask_on = QtWidgets.QPushButton(self.frame_13)
        self.mask_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mask_on.setFont(font)
        self.mask_on.setObjectName("mask_on")
        self.horizontalLayout_11.addWidget(self.mask_on)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.reserve1_label = QtWidgets.QLabel(self.frame_13)
        self.reserve1_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve1_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve1_label.setFont(font)
        self.reserve1_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve1_label.setObjectName("reserv_label")
        self.verticalLayout_11.addWidget(self.reserve1_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.reserve1_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve1_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve1_off.setFont(font)
        self.reserve1_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve1_off.setObjectName("reserv1_off")
        self.reserve1_off.setDisabled(True)
        self.horizontalLayout_9.addWidget(self.reserve1_off)
        self.reserve1_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve1_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve1_on.setFont(font)
        self.reserve1_on.setObjectName("reserv1_on")
        self.reserve1_on.setDisabled(True)
        self.horizontalLayout_9.addWidget(self.reserve1_on)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.light_label = QtWidgets.QLabel(self.frame_13)
        self.light_label.setMinimumSize(QtCore.QSize(0, 50))
        self.light_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light_label.setFont(font)
        self.light_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light_label.setObjectName("light_label")
        self.verticalLayout_12.addWidget(self.light_label)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.light_off = QtWidgets.QPushButton(self.frame_13)
        self.light_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light_off.setFont(font)
        self.light_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light_off.setObjectName("light_off")
        self.horizontalLayout_10.addWidget(self.light_off)
        self.light_on = QtWidgets.QPushButton(self.frame_13)
        self.light_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light_on.setFont(font)
        self.light_on.setObjectName("light_on")
        self.horizontalLayout_10.addWidget(self.light_on)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.reserve8_label = QtWidgets.QLabel(self.frame_13)
        self.reserve8_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve8_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve8_label.setFont(font)
        self.reserve8_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve8_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve8_label.setObjectName("reserv8_label")
        self.verticalLayout_38.addWidget(self.reserve8_label)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.reserve8_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve8_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve8_off.setFont(font)
        self.reserve8_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve8_off.setObjectName("reserv8_off")
        self.reserve8_off.setDisabled(True)
        self.horizontalLayout_36.addWidget(self.reserve8_off)
        self.reserve8_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve8_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve8_on.setFont(font)
        self.reserve8_on.setStyleSheet("")
        self.reserve8_on.setObjectName("reserv8_on")
        self.reserve8_on.setDisabled(True)
        self.horizontalLayout_36.addWidget(self.reserve8_on)
        self.verticalLayout_38.addLayout(self.horizontalLayout_36)
        self.gridLayout_4.addLayout(self.verticalLayout_38, 3, 0, 1, 1)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.reserve9_label = QtWidgets.QLabel(self.frame_13)
        self.reserve9_label.setMinimumSize(QtCore.QSize(0, 50))
        self.reserve9_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve9_label.setFont(font)
        self.reserve9_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve9_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve9_label.setObjectName("reserve9_label")
        self.verticalLayout_39.addWidget(self.reserve9_label)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.reserve9_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve9_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve9_off.setFont(font)
        self.reserve9_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve9_off.setObjectName("reserve9_off")
        self.reserve9_off.setDisabled(True)
        self.horizontalLayout_37.addWidget(self.reserve9_off)
        self.reserve9_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve9_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve9_on.setFont(font)
        self.reserve9_on.setObjectName("reserve9_on")
        self.reserve9_on.setDisabled(True)
        self.horizontalLayout_37.addWidget(self.reserve9_on)
        self.verticalLayout_39.addLayout(self.horizontalLayout_37)
        self.gridLayout_4.addLayout(self.verticalLayout_39, 3, 1, 1, 1)
        self.verticalLayout_uv9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_uv9.setObjectName("verticalLayout_uv9")
        self.ping_label = QtWidgets.QLabel(self.frame_13)
        self.ping_label.setMinimumSize(QtCore.QSize(0, 50))
        self.ping_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ping_label.setFont(font)
        self.ping_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.ping_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ping_label.setObjectName("ping_label")
        self.verticalLayout_uv9.addWidget(self.ping_label)
        self.horizontalLayout_uv9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_uv9.setObjectName("horizontalLayout_uv9")
        self.ping_off = QtWidgets.QPushButton(self.frame_13)
        self.ping_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ping_off.setFont(font)
        self.ping_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ping_off.setObjectName("ping_off")
        self.horizontalLayout_uv9.addWidget(self.ping_off)
        self.ping_on = QtWidgets.QPushButton(self.frame_13)
        self.ping_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ping_on.setFont(font)
        self.ping_on.setObjectName("ping_on")
        self.horizontalLayout_uv9.addWidget(self.ping_on)
        self.verticalLayout_uv9.addLayout(self.horizontalLayout_uv9)
        self.gridLayout_4.addLayout(self.verticalLayout_uv9, 3, 2, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_41.addWidget(self.frame_14)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem8)