from PyQt5 import QtCore, QtGui, QtWidgets


class DiagnosticTab(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setObjectName("tab_diagnostic")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem7)
        self.frame_14 = QtWidgets.QFrame(self)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_14)
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sensor_runstop = QtWidgets.QLabel(self.frame_12)
        self.sensor_runstop.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor_runstop.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_runstop.setFont(font)
        self.sensor_runstop.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_runstop.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_runstop.setObjectName("sensor_runstop")
        self.verticalLayout_9.addWidget(self.sensor_runstop)
        self.sensor_1 = QtWidgets.QLabel(self.frame_12)
        self.sensor_1.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_1.setFont(font)
        self.sensor_1.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_1.setObjectName("sensor_1")
        self.verticalLayout_9.addWidget(self.sensor_1)
        self.sensor_2 = QtWidgets.QLabel(self.frame_12)
        self.sensor_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_2.setFont(font)
        self.sensor_2.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_2.setObjectName("sensor_2")
        self.verticalLayout_9.addWidget(self.sensor_2)
        self.sensor_3 = QtWidgets.QLabel(self.frame_12)
        self.sensor_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_3.setFont(font)
        self.sensor_3.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_3.setObjectName("sensor_3")
        self.verticalLayout_9.addWidget(self.sensor_3)
        self.sensor_4 = QtWidgets.QLabel(self.frame_12)
        self.sensor_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_4.setFont(font)
        self.sensor_4.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_4.setObjectName("sensor_4")
        self.verticalLayout_9.addWidget(self.sensor_4)
        self.sensor_5 = QtWidgets.QLabel(self.frame_12)
        self.sensor_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_5.setFont(font)
        self.sensor_5.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_5.setObjectName("sensor_5")
        self.verticalLayout_9.addWidget(self.sensor_5)
        self.horizontalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setVerticalSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_46 = QtWidgets.QLabel(self.frame_13)
        self.label_46.setMinimumSize(QtCore.QSize(0, 50))
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_33.addWidget(self.label_46)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.bt_uv2_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv2_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv2_off.setFont(font)
        self.bt_uv2_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv2_off.setObjectName("bt_uv2_off")
        self.horizontalLayout_31.addWidget(self.bt_uv2_off)
        self.bt_uv2_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv2_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv2_on.setFont(font)
        self.bt_uv2_on.setObjectName("bt_uv2_on")
        self.horizontalLayout_31.addWidget(self.bt_uv2_on)
        self.verticalLayout_33.addLayout(self.horizontalLayout_31)
        self.gridLayout_4.addLayout(self.verticalLayout_33, 2, 0, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_44 = QtWidgets.QLabel(self.frame_13)
        self.label_44.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_35.addWidget(self.label_44)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.bt_uv4_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv4_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv4_off.setFont(font)
        self.bt_uv4_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv4_off.setObjectName("bt_uv4_off")
        self.horizontalLayout_33.addWidget(self.bt_uv4_off)
        self.bt_uv4_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv4_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv4_on.setFont(font)
        self.bt_uv4_on.setObjectName("bt_uv4_on")
        self.horizontalLayout_33.addWidget(self.bt_uv4_on)
        self.verticalLayout_35.addLayout(self.horizontalLayout_33)
        self.gridLayout_4.addLayout(self.verticalLayout_35, 2, 2, 1, 1)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_43 = QtWidgets.QLabel(self.frame_13)
        self.label_43.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_36.addWidget(self.label_43)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.bt_uv5_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv5_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv5_off.setFont(font)
        self.bt_uv5_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv5_off.setObjectName("bt_uv5_off")
        self.horizontalLayout_34.addWidget(self.bt_uv5_off)
        self.bt_uv5_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv5_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv5_on.setFont(font)
        self.bt_uv5_on.setObjectName("bt_uv5_on")
        self.horizontalLayout_34.addWidget(self.bt_uv5_on)
        self.verticalLayout_36.addLayout(self.horizontalLayout_34)
        self.gridLayout_4.addLayout(self.verticalLayout_36, 2, 3, 1, 1)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_42 = QtWidgets.QLabel(self.frame_13)
        self.label_42.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_37.addWidget(self.label_42)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.bt_uv6_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv6_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv6_off.setFont(font)
        self.bt_uv6_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv6_off.setObjectName("bt_uv6_off")
        self.horizontalLayout_35.addWidget(self.bt_uv6_off)
        self.bt_uv6_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv6_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv6_on.setFont(font)
        self.bt_uv6_on.setObjectName("bt_uv6_on")
        self.horizontalLayout_35.addWidget(self.bt_uv6_on)
        self.verticalLayout_37.addLayout(self.horizontalLayout_35)
        self.gridLayout_4.addLayout(self.verticalLayout_37, 2, 4, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_45 = QtWidgets.QLabel(self.frame_13)
        self.label_45.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_34.addWidget(self.label_45)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.bt_uv3_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv3_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv3_off.setFont(font)
        self.bt_uv3_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv3_off.setObjectName("bt_uv3_off")
        self.horizontalLayout_32.addWidget(self.bt_uv3_off)
        self.bt_uv3_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv3_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv3_on.setFont(font)
        self.bt_uv3_on.setObjectName("bt_uv3_on")
        self.horizontalLayout_32.addWidget(self.bt_uv3_on)
        self.verticalLayout_34.addLayout(self.horizontalLayout_32)
        self.gridLayout_4.addLayout(self.verticalLayout_34, 2, 1, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_39 = QtWidgets.QLabel(self.frame_13)
        self.label_39.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_15.addWidget(self.label_39)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.bt_fan2_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan2_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan2_off.setFont(font)
        self.bt_fan2_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_fan2_off.setObjectName("bt_fan2_off")
        self.horizontalLayout_13.addWidget(self.bt_fan2_off)
        self.bt_fan2_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan2_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan2_on.setFont(font)
        self.bt_fan2_on.setObjectName("bt_fan2_on")
        self.horizontalLayout_13.addWidget(self.bt_fan2_on)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.gridLayout_4.addLayout(self.verticalLayout_15, 1, 1, 1, 1)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_23 = QtWidgets.QLabel(self.frame_13)
        self.label_23.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_25.addWidget(self.label_23)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bt_strobe3_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_strobe3_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_strobe3_off.setFont(font)
        self.bt_strobe3_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_strobe3_off.setObjectName("bt_strobe3_off")
        self.horizontalLayout_23.addWidget(self.bt_strobe3_off)
        self.bt_strobe3_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_strobe3_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_strobe3_on.setFont(font)
        self.bt_strobe3_on.setObjectName("bt_strobe3_on")
        self.horizontalLayout_23.addWidget(self.bt_strobe3_on)
        self.verticalLayout_25.addLayout(self.horizontalLayout_23)
        self.gridLayout_4.addLayout(self.verticalLayout_25, 0, 4, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_22 = QtWidgets.QLabel(self.frame_13)
        self.label_22.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_24.addWidget(self.label_22)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bt_uv1_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv1_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv1_off.setFont(font)
        self.bt_uv1_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv1_off.setObjectName("bt_uv1_off")
        self.horizontalLayout_22.addWidget(self.bt_uv1_off)
        self.bt_uv1_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv1_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv1_on.setFont(font)
        self.bt_uv1_on.setObjectName("bt_uv1_on")
        self.horizontalLayout_22.addWidget(self.bt_uv1_on)
        self.verticalLayout_24.addLayout(self.horizontalLayout_22)
        self.gridLayout_4.addLayout(self.verticalLayout_24, 1, 4, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_40 = QtWidgets.QLabel(self.frame_13)
        self.label_40.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_22.addWidget(self.label_40)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.bt_fan3_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan3_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan3_off.setFont(font)
        self.bt_fan3_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_fan3_off.setObjectName("bt_fan3_off")
        self.horizontalLayout_20.addWidget(self.bt_fan3_off)
        self.bt_fan3_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan3_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan3_on.setFont(font)
        self.bt_fan3_on.setObjectName("bt_fan3_on")
        self.horizontalLayout_20.addWidget(self.bt_fan3_on)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.gridLayout_4.addLayout(self.verticalLayout_22, 1, 2, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_41 = QtWidgets.QLabel(self.frame_13)
        self.label_41.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_23.addWidget(self.label_41)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.bt_fan4_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan4_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan4_off.setFont(font)
        self.bt_fan4_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_fan4_off.setObjectName("bt_fan4_off")
        self.horizontalLayout_21.addWidget(self.bt_fan4_off)
        self.bt_fan4_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan4_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan4_on.setFont(font)
        self.bt_fan4_on.setObjectName("bt_fan4_on")
        self.horizontalLayout_21.addWidget(self.bt_fan4_on)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        self.gridLayout_4.addLayout(self.verticalLayout_23, 1, 3, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.frame_13)
        self.label_12.setMinimumSize(QtCore.QSize(150, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bt_fan1_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan1_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan1_off.setFont(font)
        self.bt_fan1_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_fan1_off.setObjectName("bt_fan1_off")
        self.horizontalLayout_12.addWidget(self.bt_fan1_off)
        self.bt_fan1_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_fan1_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_fan1_on.setFont(font)
        self.bt_fan1_on.setObjectName("bt_fan1_on")
        self.horizontalLayout_12.addWidget(self.bt_fan1_on)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.gridLayout_4.addLayout(self.verticalLayout_14, 1, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.frame_13)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.bt_start_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_start_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_start_off.setFont(font)
        self.bt_start_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_start_off.setObjectName("bt_start_off")
        self.horizontalLayout_11.addWidget(self.bt_start_off)
        self.bt_start_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_start_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_start_on.setFont(font)
        self.bt_start_on.setObjectName("bt_start_on")
        self.horizontalLayout_11.addWidget(self.bt_start_on)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bt_strobe2_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_strobe2_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_strobe2_off.setFont(font)
        self.bt_strobe2_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_strobe2_off.setObjectName("bt_strobe2_off")
        self.horizontalLayout_8.addWidget(self.bt_strobe2_off)
        self.bt_strobe2_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_strobe2_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_strobe2_on.setFont(font)
        self.bt_strobe2_on.setObjectName("bt_strobe2_on")
        self.horizontalLayout_8.addWidget(self.bt_strobe2_on)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bt_strobe1_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_strobe1_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_strobe1_off.setFont(font)
        self.bt_strobe1_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_strobe1_off.setObjectName("bt_strobe1_off")
        self.horizontalLayout_9.addWidget(self.bt_strobe1_off)
        self.bt_strobe1_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_strobe1_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_strobe1_on.setFont(font)
        self.bt_strobe1_on.setObjectName("bt_strobe1_on")
        self.horizontalLayout_9.addWidget(self.bt_strobe1_on)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bt_shadow_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_shadow_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_shadow_off.setFont(font)
        self.bt_shadow_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_shadow_off.setObjectName("bt_shadow_off")
        self.horizontalLayout_10.addWidget(self.bt_shadow_off)
        self.bt_shadow_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_shadow_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_shadow_on.setFont(font)
        self.bt_shadow_on.setObjectName("bt_shadow_on")
        self.horizontalLayout_10.addWidget(self.bt_shadow_on)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_47 = QtWidgets.QLabel(self.frame_13)
        self.label_47.setMinimumSize(QtCore.QSize(0, 50))
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_38.addWidget(self.label_47)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.bt_uv7_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv7_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv7_off.setFont(font)
        self.bt_uv7_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv7_off.setObjectName("bt_uv7_off")
        self.horizontalLayout_36.addWidget(self.bt_uv7_off)
        self.bt_uv7_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv7_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv7_on.setFont(font)
        self.bt_uv7_on.setStyleSheet("")
        self.bt_uv7_on.setObjectName("bt_uv7_on")
        self.horizontalLayout_36.addWidget(self.bt_uv7_on)
        self.verticalLayout_38.addLayout(self.horizontalLayout_36)
        self.gridLayout_4.addLayout(self.verticalLayout_38, 3, 0, 1, 1)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_48 = QtWidgets.QLabel(self.frame_13)
        self.label_48.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_39.addWidget(self.label_48)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.bt_uv8_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv8_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv8_off.setFont(font)
        self.bt_uv8_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv8_off.setObjectName("bt_uv8_off")
        self.horizontalLayout_37.addWidget(self.bt_uv8_off)
        self.bt_uv8_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv8_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv8_on.setFont(font)
        self.bt_uv8_on.setObjectName("bt_uv8_on")
        self.horizontalLayout_37.addWidget(self.bt_uv8_on)
        self.verticalLayout_39.addLayout(self.horizontalLayout_37)
        self.gridLayout_4.addLayout(self.verticalLayout_39, 3, 1, 1, 1)
        self.verticalLayout_uv9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_uv9.setObjectName("verticalLayout_uv9")
        self.label_uv9 = QtWidgets.QLabel(self.frame_13)
        self.label_uv9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_uv9.setFont(font)
        self.label_uv9.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.label_uv9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_uv9.setObjectName("label_uv9")
        self.verticalLayout_uv9.addWidget(self.label_uv9)
        self.horizontalLayout_uv9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_uv9.setObjectName("horizontalLayout_uv9")
        self.bt_uv9_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv9_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv9_off.setFont(font)
        self.bt_uv9_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_uv9_off.setObjectName("bt_uv9_off")
        self.horizontalLayout_uv9.addWidget(self.bt_uv9_off)
        self.bt_uv9_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_uv9_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_uv9_on.setFont(font)
        self.bt_uv9_on.setObjectName("bt_uv9_on")
        self.horizontalLayout_uv9.addWidget(self.bt_uv9_on)
        self.verticalLayout_uv9.addLayout(self.horizontalLayout_uv9)
        self.gridLayout_4.addLayout(self.verticalLayout_uv9, 3, 2, 1, 1)
        self.verticalLayout_shadow_box = QtWidgets.QVBoxLayout()
        self.verticalLayout_shadow_box.setObjectName("verticalLayout_shadow_box")
        self.label_shadow_box = QtWidgets.QLabel(self.frame_13)
        self.label_shadow_box.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_shadow_box.setFont(font)
        self.label_shadow_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_shadow_box.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shadow_box.setObjectName("label_shadow_box")
        self.verticalLayout_shadow_box.addWidget(self.label_shadow_box)
        self.horizontalLayout_shadow_box = QtWidgets.QHBoxLayout()
        self.horizontalLayout_shadow_box.setObjectName("horizontalLayout_shadow_box")
        self.bt_shadow_box_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_shadow_box_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_shadow_box_off.setFont(font)
        self.bt_shadow_box_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_shadow_box_off.setObjectName("bt_shadow_box_off")
        self.horizontalLayout_shadow_box.addWidget(self.bt_shadow_box_off)
        self.bt_shadow_box_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_shadow_box_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_shadow_box_on.setFont(font)
        self.bt_shadow_box_on.setObjectName("bt_shadow_box_on")
        self.horizontalLayout_shadow_box.addWidget(self.bt_shadow_box_on)
        self.verticalLayout_shadow_box.addLayout(self.horizontalLayout_shadow_box)
        self.gridLayout_4.addLayout(self.verticalLayout_shadow_box, 3, 3, 1, 1)
        self.verticalLayout_ping = QtWidgets.QVBoxLayout()
        self.verticalLayout_ping.setObjectName("verticalLayout_ping")
        self.label_ping = QtWidgets.QLabel(self.frame_13)
        self.label_ping.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ping.setFont(font)
        self.label_ping.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_ping.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ping.setObjectName("label_ping")
        self.verticalLayout_ping.addWidget(self.label_ping)
        self.horizontalLayout_ping = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ping.setObjectName("horizontalLayout_ping")
        self.bt_ping_off = QtWidgets.QPushButton(self.frame_13)
        self.bt_ping_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_ping_off.setFont(font)
        self.bt_ping_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.bt_ping_off.setObjectName("bt_ping_off")
        self.horizontalLayout_ping.addWidget(self.bt_ping_off)
        self.bt_ping_on = QtWidgets.QPushButton(self.frame_13)
        self.bt_ping_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_ping_on.setFont(font)
        self.bt_ping_on.setObjectName("bt_ping_on")
        self.horizontalLayout_ping.addWidget(self.bt_ping_on)
        self.verticalLayout_ping.addLayout(self.horizontalLayout_ping)
        self.gridLayout_4.addLayout(self.verticalLayout_ping, 3, 4, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_41.addWidget(self.frame_14)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem8)