from PyQt5 import QtCore, QtGui, QtWidgets


class DiagnosticTabR2(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setObjectName("tab_diagnostic")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem7)
        self.frame_14 = QtWidgets.QFrame(self)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_14)
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sensor_door = QtWidgets.QLabel(self.frame_12)
        self.sensor_door.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor_door.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sensor_door.setFont(font)
        self.sensor_door.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.sensor_door.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_door.setObjectName("sensor_door")
        self.verticalLayout_9.addWidget(self.sensor_door)
        self.reserve_1 = QtWidgets.QLabel(self.frame_12)
        self.reserve_1.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_1.setFont(font)
        self.reserve_1.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_1.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_1.setObjectName("reserve_1")
        self.verticalLayout_9.addWidget(self.reserve_1)
        self.reserve_2 = QtWidgets.QLabel(self.frame_12)
        self.reserve_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_2.setFont(font)
        self.reserve_2.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_2.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_2.setObjectName("reserve_2")
        self.verticalLayout_9.addWidget(self.reserve_2)
        self.reserve_3 = QtWidgets.QLabel(self.frame_12)
        self.reserve_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_3.setFont(font)
        self.reserve_3.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_3.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_3.setObjectName("sensor_3")
        self.verticalLayout_9.addWidget(self.reserve_3)
        self.reserve_4 = QtWidgets.QLabel(self.frame_12)
        self.reserve_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.reserve_4.setFont(font)
        self.reserve_4.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.reserve_4.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_4.setObjectName("reserve_4")
        self.verticalLayout_9.addWidget(self.reserve_4)
        self.ping_input = QtWidgets.QLabel(self.frame_12)
        self.ping_input.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ping_input.setFont(font)
        self.ping_input.setStyleSheet("background-color: rgb(117, 123, 127);")
        self.ping_input.setAlignment(QtCore.Qt.AlignCenter)
        self.ping_input.setObjectName("ping_input")
        self.verticalLayout_9.addWidget(self.ping_input)
        self.horizontalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setVerticalSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.light4_label = QtWidgets.QLabel(self.frame_13)
        self.light4_label.setMinimumSize(QtCore.QSize(0, 50))
        self.light4_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light4_label.setFont(font)
        self.light4_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light4_label.setObjectName("light4_label")
        self.verticalLayout_33.addWidget(self.light4_label)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.light4_off = QtWidgets.QPushButton(self.frame_13)
        self.light4_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light4_off.setFont(font)
        self.light4_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light4_off.setObjectName("light4_off")
        self.horizontalLayout_31.addWidget(self.light4_off)
        self.light4_blink = QtWidgets.QPushButton(self.frame_13)
        self.light4_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light4_blink.setFont(font)
        self.light4_blink.setObjectName("light4_blink")
        self.horizontalLayout_31.addWidget(self.light4_blink)
        self.light4_on = QtWidgets.QPushButton(self.frame_13)
        self.light4_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light4_on.setFont(font)
        self.light4_on.setObjectName("light4_on")
        self.horizontalLayout_31.addWidget(self.light4_on)
        self.verticalLayout_33.addLayout(self.horizontalLayout_31)
        self.gridLayout_4.addLayout(self.verticalLayout_33, 2, 0, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.light6_label = QtWidgets.QLabel(self.frame_13)
        self.light6_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light6_label.setFont(font)
        self.light6_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light6_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light6_label.setObjectName("light6_label")
        self.verticalLayout_35.addWidget(self.light6_label)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.light6_off = QtWidgets.QPushButton(self.frame_13)
        self.light6_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light6_off.setFont(font)
        self.light6_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light6_off.setObjectName("light6_off")
        self.horizontalLayout_33.addWidget(self.light6_off)
        self.light6_blink = QtWidgets.QPushButton(self.frame_13)
        self.light6_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light6_blink.setFont(font)
        self.light6_blink.setObjectName("light6_blink")
        self.horizontalLayout_33.addWidget(self.light6_blink)
        self.light6_on = QtWidgets.QPushButton(self.frame_13)
        self.light6_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light6_on.setFont(font)
        self.light6_on.setObjectName("light6_on")
        self.horizontalLayout_33.addWidget(self.light6_on)
        self.verticalLayout_35.addLayout(self.horizontalLayout_33)
        self.gridLayout_4.addLayout(self.verticalLayout_35, 2, 2, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.light5_label = QtWidgets.QLabel(self.frame_13)
        self.light5_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light5_label.setFont(font)
        self.light5_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light5_label.setObjectName("light5_label")
        self.verticalLayout_34.addWidget(self.light5_label)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.light5_off = QtWidgets.QPushButton(self.frame_13)
        self.light5_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light5_off.setFont(font)
        self.light5_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light5_off.setObjectName("light5_off")
        self.horizontalLayout_32.addWidget(self.light5_off)
        self.light5_blink = QtWidgets.QPushButton(self.frame_13)
        self.light5_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light5_blink.setFont(font)
        self.light5_blink.setObjectName("light5_blink")
        self.horizontalLayout_32.addWidget(self.light5_blink)
        self.light5_on = QtWidgets.QPushButton(self.frame_13)
        self.light5_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light5_on.setFont(font)
        self.light5_on.setObjectName("light5_on")
        self.horizontalLayout_32.addWidget(self.light5_on)
        self.verticalLayout_34.addLayout(self.horizontalLayout_32)
        self.gridLayout_4.addLayout(self.verticalLayout_34, 2, 1, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.light2_label = QtWidgets.QLabel(self.frame_13)
        self.light2_label.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light2_label.setFont(font)
        self.light2_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light2_label.setObjectName("light2_label")
        self.verticalLayout_24.addWidget(self.light2_label)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.light2_off = QtWidgets.QPushButton(self.frame_13)
        self.light2_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light2_off.setFont(font)
        self.light2_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light2_off.setObjectName("light2_off")
        self.horizontalLayout_22.addWidget(self.light2_off)
        self.light2_blink = QtWidgets.QPushButton(self.frame_13)
        self.light2_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light2_blink.setFont(font)
        self.light2_blink.setObjectName("light2_blink")
        self.horizontalLayout_22.addWidget(self.light2_blink)
        self.light2_on = QtWidgets.QPushButton(self.frame_13)
        self.light2_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light2_on.setFont(font)
        self.light2_on.setObjectName("light2_on")
        self.horizontalLayout_22.addWidget(self.light2_on)
        self.verticalLayout_24.addLayout(self.horizontalLayout_22)
        self.gridLayout_4.addLayout(self.verticalLayout_24, 1, 1, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.light3_label = QtWidgets.QLabel(self.frame_13)
        self.light3_label.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light3_label.setFont(font)
        self.light3_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light3_label.setObjectName("light3_label")
        self.verticalLayout_22.addWidget(self.light3_label)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.light3_off = QtWidgets.QPushButton(self.frame_13)
        self.light3_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light3_off.setFont(font)
        self.light3_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light3_off.setObjectName("light3_off")
        self.horizontalLayout_20.addWidget(self.light3_off)
        self.light3_blink = QtWidgets.QPushButton(self.frame_13)
        self.light3_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light3_blink.setFont(font)
        self.light3_blink.setObjectName("light3_blink")
        self.horizontalLayout_20.addWidget(self.light3_blink)
        self.light3_on = QtWidgets.QPushButton(self.frame_13)
        self.light3_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light3_on.setFont(font)
        self.light3_on.setObjectName("light3_on")
        self.horizontalLayout_20.addWidget(self.light3_on)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.gridLayout_4.addLayout(self.verticalLayout_22, 1, 2, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.light1_label = QtWidgets.QLabel(self.frame_13)
        self.light1_label.setMinimumSize(QtCore.QSize(150, 0))
        self.light1_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light1_label.setFont(font)
        self.light1_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light1_label.setObjectName("light1_label")
        self.verticalLayout_14.addWidget(self.light1_label)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.light1_off = QtWidgets.QPushButton(self.frame_13)
        self.light1_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light1_off.setFont(font)
        self.light1_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light1_off.setObjectName("light1_off")
        self.horizontalLayout_12.addWidget(self.light1_off)
        self.light1_blink = QtWidgets.QPushButton(self.frame_13)
        self.light1_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light1_blink.setFont(font)
        self.light1_blink.setObjectName("light1_blink")
        self.horizontalLayout_12.addWidget(self.light1_blink)
        self.light1_on = QtWidgets.QPushButton(self.frame_13)
        self.light1_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light1_on.setFont(font)
        self.light1_on.setObjectName("light1_on")
        self.horizontalLayout_12.addWidget(self.light1_on)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.gridLayout_4.addLayout(self.verticalLayout_14, 1, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.spot_label = QtWidgets.QLabel(self.frame_13)
        self.spot_label.setMinimumSize(QtCore.QSize(0, 50))
        self.spot_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spot_label.setFont(font)
        self.spot_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.spot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.spot_label.setObjectName("spot_label")
        self.verticalLayout_13.addWidget(self.spot_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spot_off = QtWidgets.QPushButton(self.frame_13)
        self.spot_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spot_off.setFont(font)
        self.spot_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.spot_off.setObjectName("spot_off")
        self.horizontalLayout_11.addWidget(self.spot_off)
        self.spot_on = QtWidgets.QPushButton(self.frame_13)
        self.spot_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spot_on.setFont(font)
        self.spot_on.setObjectName("spot_on")
        self.horizontalLayout_11.addWidget(self.spot_on)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.animator_start_label = QtWidgets.QLabel(self.frame_13)
        self.animator_start_label.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.animator_start_label.setFont(font)
        self.animator_start_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.animator_start_label.setAlignment(QtCore.Qt.AlignCenter)
        self.animator_start_label.setObjectName("animator_start_label")
        self.verticalLayout_11.addWidget(self.animator_start_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.animator_start_off = QtWidgets.QPushButton(self.frame_13)
        self.animator_start_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.animator_start_off.setFont(font)
        self.animator_start_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.animator_start_off.setObjectName("animator_start_off")
        self.horizontalLayout_9.addWidget(self.animator_start_off)
        self.animator_start_on = QtWidgets.QPushButton(self.frame_13)
        self.animator_start_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.animator_start_on.setFont(font)
        self.animator_start_on.setObjectName("animator_start_on")
        self.horizontalLayout_9.addWidget(self.animator_start_on)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.blinker_label = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.blinker_label.setFont(font)
        self.blinker_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.blinker_label.setAlignment(QtCore.Qt.AlignCenter)
        self.blinker_label.setObjectName("blinker_label")
        self.verticalLayout_12.addWidget(self.blinker_label)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.blinker_off = QtWidgets.QPushButton(self.frame_13)
        self.blinker_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.blinker_off.setFont(font)
        self.blinker_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.blinker_off.setObjectName("blinker_off")
        self.horizontalLayout_10.addWidget(self.blinker_off)
        self.blinker_on = QtWidgets.QPushButton(self.frame_13)
        self.blinker_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.blinker_on.setFont(font)
        self.blinker_on.setObjectName("blinker_on")
        self.horizontalLayout_10.addWidget(self.blinker_on)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.light7_label = QtWidgets.QLabel(self.frame_13)
        self.light7_label.setMinimumSize(QtCore.QSize(0, 50))
        self.light7_label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light7_label.setFont(font)
        self.light7_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.light7_label.setAlignment(QtCore.Qt.AlignCenter)
        self.light7_label.setObjectName("light7_label")
        self.verticalLayout_38.addWidget(self.light7_label)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.light7_off = QtWidgets.QPushButton(self.frame_13)
        self.light7_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light7_off.setFont(font)
        self.light7_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.light7_off.setObjectName("light7_off")
        self.horizontalLayout_36.addWidget(self.light7_off)
        self.light7_blink = QtWidgets.QPushButton(self.frame_13)
        self.light7_blink.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light7_blink.setFont(font)
        self.light7_blink.setStyleSheet("")
        self.light7_blink.setObjectName("light7_blink")
        self.horizontalLayout_36.addWidget(self.light7_blink)
        self.light7_on = QtWidgets.QPushButton(self.frame_13)
        self.light7_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.light7_on.setFont(font)
        self.light7_on.setStyleSheet("")
        self.light7_on.setObjectName("light7_on")
        self.horizontalLayout_36.addWidget(self.light7_on)
        self.verticalLayout_38.addLayout(self.horizontalLayout_36)
        self.gridLayout_4.addLayout(self.verticalLayout_38, 3, 0, 1, 1)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.reserve_label = QtWidgets.QLabel(self.frame_13)
        self.reserve_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve_label.setFont(font)
        self.reserve_label.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.reserve_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reserve_label.setObjectName("reserve_label")
        self.verticalLayout_39.addWidget(self.reserve_label)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.reserve_off = QtWidgets.QPushButton(self.frame_13)
        self.reserve_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve_off.setFont(font)
        self.reserve_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.reserve_off.setObjectName("reserve_off")
        self.reserve_off.setDisabled(True)
        self.horizontalLayout_37.addWidget(self.reserve_off)
        self.reserve_on = QtWidgets.QPushButton(self.frame_13)
        self.reserve_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reserve_on.setFont(font)
        self.reserve_on.setObjectName("reserve_on")
        self.reserve_on.setDisabled(True)
        self.horizontalLayout_37.addWidget(self.reserve_on)
        self.verticalLayout_39.addLayout(self.horizontalLayout_37)
        self.gridLayout_4.addLayout(self.verticalLayout_39, 3, 1, 1, 1)
        self.verticalLayout_uv9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_uv9.setObjectName("verticalLayout_uv9")
        self.ping_label = QtWidgets.QLabel(self.frame_13)
        self.ping_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ping_label.setFont(font)
        self.ping_label.setStyleSheet("background-color: rgb(255, 191, 0);")
        self.ping_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ping_label.setObjectName("ping_label")
        self.verticalLayout_uv9.addWidget(self.ping_label)
        self.horizontalLayout_uv9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_uv9.setObjectName("horizontalLayout_uv9")
        self.ping_off = QtWidgets.QPushButton(self.frame_13)
        self.ping_off.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ping_off.setFont(font)
        self.ping_off.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ping_off.setObjectName("ping_off")
        self.horizontalLayout_uv9.addWidget(self.ping_off)
        self.ping_on = QtWidgets.QPushButton(self.frame_13)
        self.ping_on.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ping_on.setFont(font)
        self.ping_on.setObjectName("ping_on")
        self.horizontalLayout_uv9.addWidget(self.ping_on)
        self.verticalLayout_uv9.addLayout(self.horizontalLayout_uv9)
        self.gridLayout_4.addLayout(self.verticalLayout_uv9, 3, 2, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_41.addWidget(self.frame_14)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_41.addItem(spacerItem8)