class TimeBox():
	def __init__(self, filename):
		with open(filename, 'r') as f:
			f.readline()			
			self.t1 = int(f.readline())
			f.readline()
			f.readline()
			self.t2 = int(f.readline())
			f.readline()
			f.readline()
			self.t4 = int(f.readline())
			f.readline()
			f.readline()
			self.t5 = int(f.readline())
			f.readline()
			f.readline()
			self.t9 = int(f.readline())
			f.readline()
			f.readline()
			self.t10 = int(f.readline())
			f.readline()
			f.readline()
			self.t12 = int(f.readline())
			f.readline()
			f.readline()
			self.t13 = int(f.readline())
			f.readline()
			f.readline()
			self.t14 = int(f.readline())
			f.readline()
			f.readline()
			self.t15 = int(f.readline())
			f.readline()
			f.readline()
			self.t16 = int(f.readline())
			f.readline()
			f.readline()
			self.t17 = int(f.readline())
			f.readline()
			f.readline()
			self.t18 = int(f.readline())
			f.readline()
			f.readline()
			self.t19 = int(f.readline())
			f.readline()
			f.readline()
			self.t20 = int(f.readline())
			f.readline()
			f.readline()
			self.t21 = int(f.readline())
			f.readline()
			f.readline()
			self.t22 = float(f.readline())